-- MySQL Script generated by MySQL Workbench
-- 09/21/16 16:15:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema micro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema micro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `micro` DEFAULT CHARACTER SET utf8 ;
USE `micro` ;

-- -----------------------------------------------------
-- Table `micro`.`Yoneticiler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micro`.`Yoneticiler` (
  `yonetici_id` INT NOT NULL AUTO_INCREMENT,
  `ad` VARCHAR(50) NULL,
  `soyad` VARCHAR(50) NULL,
  `eposta` VARCHAR(100) NULL,
  `sifre` VARCHAR(50) NULL,
  `kayit_tarihi` DATE NULL,
  PRIMARY KEY (`yonetici_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micro`.`Sayfalar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micro`.`Sayfalar` (
  `sayfa_id` INT NOT NULL AUTO_INCREMENT,
  `adi` VARCHAR(45) NULL,
  `iceirk` LONGTEXT NULL,
  `kayit_tarihi` VARCHAR(45) NULL,
  `thumbnail` VARCHAR(145) NULL,
  `meta_desc` VARCHAR(45) NULL,
  `meta_keywords` VARCHAR(45) NULL,
  PRIMARY KEY (`sayfa_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micro`.`Iletisim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micro`.`Iletisim` (
  `firma_id` INT NOT NULL AUTO_INCREMENT,
  `firma_adi` VARCHAR(100) NULL,
  `vergi_numarasi` VARCHAR(45) NULL,
  `adresi` VARCHAR(255) NULL,
  `telefon` VARCHAR(45) NULL,
  `web` VARCHAR(45) NULL,
  `eposta` VARCHAR(100) NULL,
  `fax` VARCHAR(45) NULL,
  `map_url` VARCHAR(140) NULL,
  `thumbnail` VARCHAR(145) NULL,
  PRIMARY KEY (`firma_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micro`.`Galeri`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micro`.`Galeri` (
  `resim_id` INT NOT NULL,
  `altyazı` VARCHAR(45) NULL,
  `resimler` VARCHAR(85) NULL,
  `kayit_tarihi` DATE NULL,
  `thumbnail` VARCHAR(145) NULL,
  `meta_desc` VARCHAR(45) NULL,
  `meta_keywords` VARCHAR(45) NULL,
  `adi` VARCHAR(45) NULL,
  PRIMARY KEY (`resim_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micro`.`Referanslar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micro`.`Referanslar` (
  `referans_id` INT NOT NULL AUTO_INCREMENT,
  `adi` VARCHAR(45) NULL,
  `thumbnail` VARCHAR(240) NULL,
  `kayit_tarihi` DATE NULL,
  `icerik` LONGTEXT NULL,
  `thumbnail` VARCHAR(215) NULL,
  `meta_desc` VARCHAR(45) NULL,
  `meta_keywords` VARCHAR(45) NULL,
  PRIMARY KEY (`referans_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micro`.`Takim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micro`.`Takim` (
  `takim_id` INT NOT NULL AUTO_INCREMENT,
  `adi` VARCHAR(45) NULL,
  `kayit_tarihi` DATE NULL,
  `icerik` LONGTEXT NULL,
  `thumbnail` VARCHAR(245) NULL,
  `soyadi` VARCHAR(30) NULL,
  `unvan` VARCHAR(45) NULL,
  `eposta` VARCHAR(50) NULL,
  `telefon` VARCHAR(45) NULL,
  `meta_desc` VARCHAR(45) NULL,
  `meta_keywords` VARCHAR(45) NULL,
  PRIMARY KEY (`takim_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micro`.`Sosyal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micro`.`Sosyal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sosyal_ag` VARCHAR(45) NULL,
  `url` LONGTEXT NULL,
  `sosyal_resmi` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `micro`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `micro`.`Menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adi` VARCHAR(45) NULL,
  `url` LONGTEXT NULL,
  `isHeader` TINYINT(1) NULL,
  `isFooter` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
